ALTER TABLE "Client" ADD COLUMN "rg" VARCHAR(20);
ALTER TABLE "Client" ADD COLUMN "street" TEXT;
ALTER TABLE "Client" ADD COLUMN "city" VARCHAR(120);
ALTER TABLE "Client" ADD COLUMN "state" VARCHAR(2);
ALTER TABLE "Client" ADD COLUMN "zipCode" VARCHAR(8);
